name: khalti_checkout_core
description: An official wrapper around Khalti Payment Gateway's REST API.
version: 1.2.0
homepage: https://khalti.com/payment-gateway/
documentation: https://docs.khalti.com/
issue_tracker: https://github.com/khalti/khalti-flutter-sdk/issues
repository: https://github.com/khalti/khalti-flutter-sdk/tree/master/packages/khalti_core

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  meta: ^1.11.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^3.0.1
  mocktail: ^1.0.3
  package_info_plus_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.1.8
  test: ^1.25.2
